### ISSUE TITLE
Lost Block on View Change

### ISSUE THREAD

**Issue by coltonfike** [coltonfike/quorum#4]
Occasionally, a block gets lost when view change happens. I can only reproduce this when transactions are being sent, as the problem doesn't occur on empty blocks. This lost block results in lost transactions, so this needs to be fixed.

**Comment by ColtonFike** [comment]
Following up on this after looking some more. The current problem is that blocks are produced very rapidly after view change finishes. Blocks arrive out of order to the nodes, so the nodes request the missing blocks, but for some reason, responses aren't being received. Here are log files for future reference:
[logs_node1.txt](https://github.com/ColtonFike/quorum/files/7079893/logs_node1.txt)
[logs_node2.txt](https://github.com/ColtonFike/quorum/files/7079894/logs_node2.txt)
[logs_node3.txt](https://github.com/ColtonFike/quorum/files/7079895/logs_node3.txt)
[logs_node4.txt](https://github.com/ColtonFike/quorum/files/7079899/logs_node4.txt)
